/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clientesservidores;

import java.awt.Color;
import javax.swing.border.AbstractBorder;

/**
 *
 * @author Carlos
 */
public class MensajeView extends javax.swing.JPanel {

    public String id;
    public String mensaje;
    
    public Index index;
    public MensajeView() {
        initComponents();
        // AbstractBorder brdr = new TextBubbleBorder(Color.BLACK,2,16,0);
        //setBorder(brdr);
        this.setOpaque(false);
        this.setBackground(new Color(255,255,255,0));
    }

    public void setMensaje(String mensaje) {
        this.mensaje = mensaje;
        this.text.setText(mensaje);
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public void setSizeText(int x,int y){
        this.text.setSize(x, y);
    }


    public void setIndex(Index index) {
        this.index = index;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        text = new javax.swing.JEditorPane();

        text.setEditable(false);
        text.setBackground(new java.awt.Color(152, 184, 203));
        text.setBorder(null);
        text.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(text, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(text, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane text;
    // End of variables declaration//GEN-END:variables
}
